# Use sonar/sonar as user/password credentials
version: '3.1'

services:
  sonarqube:
    image: sonarqube:5.6.6
#     image: sonarqube:lts    
    container_name: rapidvalue-sonarqube
    depends_on:
      - db
    networks:
     - sonarqube-network
    ports:
     - "9000:9000"
     - "3306:3306"
    environment:
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
     - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

  db:
    image: mysql:5.7
#    image: mysql:lts
    container_name: rapidvalue-sonarqube-mysql
    networks:
      - sonarqube-network
    environment:
     - MYSQL_ROOT_PASSWORD=sonar
     - MYSQL_DATABASE=sonar
     - MYSQL_USER=sonar
     - MYSQL_PASSWORD=sonar
     
networks:
  sonarqube-network: